routes/web_routes.py
from flask import Blueprint, render_template, url_for, redirect, flash
from flask_login import login_required, current_user, login_user, logout_user
from flask_bcrypt import Bcrypt
from sqlalchemy import func

web_routes_bp = Blueprint('web_routes', __name__, static_folder='static', static_url_path='/static')

bcrypt = Bcrypt()

@web_routes_bp.route('/', methods=['GET', 'POST'])
@login_required
def dashboard(): 
    
    from app import User, Measurement, db
    measurements = Measurement.query.all() 
    max_timestamp = db.session.query(Measurement.timestamp).filter(Measurement.id == db.session.query(db.func.max(Measurement.id))).scalar()
    max_temp = db.session.query(Measurement.temp).filter(Measurement.id == db.session.query(db.func.max(Measurement.id))).scalar()
    return render_template('dashboard.html', name=current_user.username, measured_values=measurements, max_timestamp=max_timestamp, max_temp = max_temp) 

@web_routes_bp.route('/login', methods=['GET', 'POST'])
def login(): 
    from app import LoginForm, User
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user:
            if bcrypt.check_password_hash(user.password, form.password.data):
                login_user(user)
                return redirect(url_for('web_routes.dashboard'))
    return render_template('login.html', form=form)  

@web_routes_bp.route('/logout', methods=['GET', 'POST'])
@login_required
def logout():
    logout_user()
    return redirect(url_for('web_routes.login'))

@web_routes_bp.route('/register', methods=['GET', 'POST'])
def register():  
    from app import RegisterForm, User, db
    form = RegisterForm()
    if form.validate_on_submit():

        username = form.username.data

        # Kontrola, zda uživatelské jméno již existuje
        existing_user = User.query.filter_by(username=username).first()
        if existing_user:
            flash('That username is already taken. Please choose a different one.', 'danger')
            return render_template('register.html', form=form)
    
        hashed_password = bcrypt.generate_password_hash(form.password.data)
        new_user = User(username=form.username.data, password=hashed_password)
        db.session.add(new_user)
        db.session.commit()
        
        # Automatické přihlášení nově registrovaného uživatele
        login_user(new_user)
        return redirect(url_for('web_routes.dashboard'))  # Přesměrování na dashboard po registraci

    return render_template('register.html', form=form)  

templates/base.html
<html lang="cs">  
<head>  
    <title>NSI Project</title>  
    
 
    <!-- BOOTSTRAP https://getbootstrap.com/ --> 
    <!-- tohle by mohl být ten index html--> 
    <link 
        href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" 
        rel="stylesheet" 
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" 
        crossorigin="anonymous">  
    <script 
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" 
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" 
        crossorigin="anonymous">
    </script>  
 
</head>  
<body>  

    {% include "navbar.html "%}
    <br/>
    <div class = "container">
        {% block content %}
        {% endblock %}  
    </div>
      
 
</body>  
</html>

templates/dashboard.html
{% extends "base.html" %}

{% block content %}

<link rel="stylesheet" href="{{url_for('static', filename='style.css')}}">
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>


<div class="container">
    <div class="row">
        <!-- Kontejner s nápisy -->
        <div class="col-md-6">
            <h1>Welcome, {{ name }}!</h1>
            <form class="form-dashboard" id="DashBoard_heading">
                <h2 class="form-signin-heading">Last measured value:</h2>
                {% if not measured_values %}
                <p>No data found</p>
                {% else %}
                <p id="TimeStamp">Timestamp: {{max_timestamp}}</p> 
                <p id="Temp">Temperature: {{max_temp}}</p>
                {% endif %}
            </form>

            <!-- Tabulka -->
            <div class="container-md-6">
                <table id="measuredValuesTable" class="table table-responsive table-bordered table-custom border-dark table-hover text-center text-capitalize">
                    <thead class="table-dark table-active text-uppercase text-white">
                        <tr>
                            <th>Timestamp</th>
                            <th>Temperature</th>    
                        </tr>
                    </thead>
                    <tbody>
                        {% if not measured_values %}
                        <tr>
                            <td colspan="2">No data found</td>
                        </tr> 
                        {% else %}
                        {% for task in measured_values|reverse %}
                        <tr>
                            <td>{{ task.timestamp }}</td>
                            <td>{{ task.temp }} °C</td>
                        </tr>   
                        {% endfor %} 
                        {% endif %}
                    </tbody>
                </table>
            </div>
        </div>

        <!-- Custom input group 1 -->
        <div class="col-md-6">
            <div class="form-container">
                <div class="custom-input-group">
                    <input type="text" class="custom-input" id="numberOfValues" placeholder="Number of last measured values" aria-label="Number of last measured values" aria-describedby="basic-addon2">
                    <button onclick="performGet()" class="custom-button btn btn-outline-secondary" type="button" >Confirm</button>
                </div>
                <!-- Custom input group 2 -->
                <div class="custom-input-group mt-3">
                    <input type="text" class="custom-input" id="numToDelete" placeholder="Number of values you want to delete" aria-label="Number of values you want to delete" aria-describedby="basic-addon2">
                    <button onclick="deleteLast()" class="custom-button btn btn-outline-secondary" type="button" >Confirm</button>
                </div>
                <!-- Formulář pro přidání úkolu -->
                <div class="card mt-3">
                    <div class="card-body">
                        <form id="add-task-form">
                            <div class="mb-3">
                                <input type="text" class="form-control" id="timestamp" placeholder="timestamp">
                            </div>
                            <div class="mb-3">
                                <input type="text" class="form-control" id="temp" placeholder="temp">
                            </div>
                            <button onclick="performPost()" class="btn btn-primary">Přidat</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>

        
    </div>





</div>


<script>

    function performGet()
    {
        var taskId = $('#numberOfValues').val();
        $.ajax({
            url: '/api/tasks/' + taskId,
            type: 'GET',
            success: function(response) {
                // Vymažeme obsah tabulky
                $('#measuredValuesTable tbody').empty();

                // Pokud byla nalezena odpověď, nahraju nové hodnoty
                if (response.length > 0) {
                    response.forEach(function(task) {
                        $('#measuredValuesTable tbody').append('<tr><td>' + task.timestamp + '</td><td>' + task.temp + '°C</td></tr>');
                    });
                    UpdateTemp()
                    UpdateTimeStamp()
                } else {
                    // Pokud nebyly nalezeny žádné údaje, zobrazím zprávu "No data found"
                    $('#measuredValuesTable tbody').append('<tr><td colspan="2">No data found</td></tr>');
                }
            }
        });
        $('#numberOfValues').val('');
        $('#numberOfValues').attr('placeholder', 'Number of last measured values');
    }

    function performPost() {
    var timestamp = $('#timestamp').val();
    var temp = $('#temp').val();
    $.ajax({
        url: '/api/tasks',
        type: 'POST',
        contentType: 'application/json',
        data: JSON.stringify({ "timestamp": timestamp, "temp": parseFloat(temp) }),  // Převést teplotu na float, pokud je potřeba
        success: function(response) {
            console.log("Úspěšně odesláno do databáze:", response);
            // Pro další akce po úspěšném odeslání dat
            UpdateTemp()
            UpdateTimeStamp()
        },
        error: function(xhr, status, error) {
            console.error("Chyba při odesílání dat do databáze:", error);
            console.error(xhr.responseText);  // Vypíše detaily chyby zpět z serveru
        }
    });
    }


    function deleteLast() {
    var numToDelete = $('#numToDelete').val();
    $.ajax({
        url: '/api/delete_last/' + numToDelete,
        type: 'DELETE',
        success: function(response) {
            // Vymažeme obsah tabulky
            $('#measuredValuesTable tbody').empty();

            // Pokud byla nalezena odpověď, nahraju nové hodnoty
            if (response.length > 0) {
                response.forEach(function(task) {
                    $('#measuredValuesTable tbody').append('<tr><td>' + task.timestamp + '</td><td>' + task.temp + '°C</td></tr>');
                });
                UpdateTemp()
                UpdateTimeStamp()
            } else {
                // Pokud nebyly nalezeny žádné údaje, zobrazím zprávu "No data found"
                $('#measuredValuesTable tbody').append('<tr><td colspan="2">No data found</td></tr>');
                $('#DashBoard_heading p').remove(); // Odstranit existující zprávu "No data found"
                $('#DashBoard_heading ').append('<p>No data found</p>');
            }
        },
        
    });
    $('#numToDelete').val('');
    $('#numToDelete').attr('placeholder', 'Number of values you want to delete');
    }

    // Funkce pro aktualizaci zprávy na stránce
    function UpdateTemp() {
        $.ajax({
            url: '/api/update_temp',
            type: 'GET',
            success: function(response) {
                $('#Temp').text("Temperature: " + response + "°C");
            },
            error: function(xhr, status, error) {
                console.error("Chyba při odesílání dat do databáze:", error);
                console.error(xhr.responseText);  // Vypíše detaily chyby zpět z serveru
            }
        });   
    }

    function UpdateTimeStamp() {
        $.ajax({
            url: '/api/update_timestamp',
            type: 'GET',
            success: function(response) {
                $('#TimeStamp').text("Timestamp: " + response);
            },
            error: function(xhr, status, error) {
                console.error("Chyba při odesílání dat do databáze:", error);
                console.error(xhr.responseText);  // Vypíše detaily chyby zpět z serveru
            }
        });   
    }

    // Funkce pro získání nových zpráv z ESP32 pomocí AJAX
    function getValue() {
        $.ajax({
            url: '/api/get_value', // URL pro získání zprávy z ESP32
            type: 'GET',
            success: function(response) {
                // Vymažeme obsah tabulky
                $('#measuredValuesTable tbody').empty();

                // Pokud byla nalezena odpověď, nahraju nové hodnoty
                if (response.length > 0) {
                    response.forEach(function(task) {
                        $('#measuredValuesTable tbody').append('<tr><td>' + task.timestamp + '</td><td>' + task.temp + '°C</td></tr>');
                    });
                    UpdateTemp()
                    UpdateTimeStamp()
                } else {
                    // Pokud nebyly nalezeny žádné údaje, zobrazím zprávu "No data found"
                    $('#measuredValuesTable tbody').append('<tr><td colspan="2">No data found</td></tr>');
                    $('#DashBoard_heading p').remove(); // Odstranit existující zprávu "No data found"
                    $('#DashBoard_heading ').append('<p>No data found</p>');
                }
            },
        });
    }

    // Periodicky volání funkce pro získání nových zpráv (např. každých 5 sekund)
    setInterval(getValue, 5000);

</script>


{% endblock %}

templates/login.html
{% extends "base.html" %}

{% block content %}

<link rel="stylesheet" href="{{url_for('static', filename='style.css')}}">



<div class="container">

    <form class="form-signin" method='POST' action="">
        <h2 class="form-signin-heading">Login</h2>
        {{ form.hidden_tag() }}
    
        <div class="form-group">
            <label for="username">Username:</label>
            {{ form.username(class="form-control", placeholder="Enter your username") }}
        </div>
    
        <div class="form-group">
            <label for="password">Password:</label>
            {{ form.password(class="form-control", placeholder="Enter your password") }}
        </div>
    
        <button class="btn btn-lg btn-primary btn-block" type="submit">Login</button>
    </form>

  </div> <!-- /container -->
{% endblock %}

templates/navbar.html
<nav class="navbar navbar-expand-lg bg-dark navbar-dark">
  <div class="container-fluid">
      <a class="navbar-brand">NSI Project</a>
      <div class="collapse navbar-collapse justify-content-between" id="navbarNav">
          <ul class="navbar-nav">
            {% if name and request.endpoint == 'web_routes.dashboard' %}
              <li class="nav-item">
                  <span class="navbar-text text-white">User: {{name}}</span>
              </li>
            {% endif %}
          </ul>
          <ul class="navbar-nav">
              <li class="nav-item">
                  <a class="nav-link text-white" href="{{url_for('web_routes.login')}}">Login/out</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link text-white" href="{{url_for('web_routes.register')}}">Register</a>
              </li>
              
          </ul>
      </div>
  </div>
</nav>

templates/register.html
{% extends "base.html" %}

{% block content %}


<link rel="stylesheet" href="{{url_for('static', filename='style.css')}}">

<div class="container">

    <form class="form-signin" method='POST' action="">
        <h2 class="form-signin-heading">Register</h2>
        {{ form.hidden_tag() }}
    
        <div class="form-group">
            <label for="username">Username:</label>
            {{ form.username(class="form-control", placeholder="Enter your username") }}
        </div>
    
        <div class="form-group">
            <label for="password">Password:</label>
            {{ form.password(class="form-control", placeholder="Enter your password") }}
        </div>
    
        <button class="btn btn-lg btn-primary btn-block" type="submit">Register</button>

    </form>
  
  </div> <!-- /container -->
{% endblock %}